export const actionTypes = {
    AUTH: 'AUTH',
    SET_AUTH_LOADING: 'SET_AUTH_LOADING',
    END_AUTH_LOADING: 'END_AUTH_LOADING',
    LOGOUT: 'LOGOUT',
    SET_COURSE_LOADING: 'SET_COURSE_LOADING',
    END_COURSE_LOADING: 'END_COURSE_LOADING',
    GET_COURSE: 'GET_COURSE',
    SET_COURSES_LOADING: 'SET_COURSES_LOADING',
    END_COURSES_LOADING: 'END_COURSES_LOADING',
    GET_COURSES: 'GET_COURSES',
    GET_COURSES_ADMIN: 'GET_COURSES_ADMIN',
    ERROR: 'ERROR',
}
